"""English/Hindi presentation strings; calculations always retain canonical values."""

TRANSLATIONS = {
    "en": {
        "language": "Language", "english": "English", "hindi": "Hindi", "app_title": "Kundali AI", "app_subtitle": "AI-powered Vedic Astrology & Birth Chart Analysis", "birth_details": "Birth Details", "birth_summary": "Birth Summary", "birth_time": "Birth Time", "generate_new": "Enter your birth details in the sidebar and generate your Kundali.",
        "app_caption": "Sidereal Vedic chart calculations using Swiss Ephemeris and Lahiri Ayanamsa.",
        "name": "Name", "dob": "Date of Birth", "day": "Day", "month": "Month", "year": "Year", "time": "Time of Birth", "gender": "Gender", "place": "Place of Birth", "generate": "Generate Kundali",
        "select_gender": "Select gender", "female": "Female", "male": "Male", "non_binary": "Non-binary", "prefer_not": "Prefer not to say",
        "overview": "Overview", "d1_tab": "Lagna Chart (D1)", "d9_tab": "Navamsa Chart (D9)", "d10_tab": "Dashamsa Chart (D10)", "positions_tab": "Planetary Positions", "dasha_tab": "Vimshottari Dasha", "ai_tab": "AI Interpretation",
        "basic": "Basic", "charts": "Charts", "kp": "KP", "ashtakavarga": "Ashtakavarga", "dasha": "Dasha", "report": "Report", "lagna": "Lagna", "navamsa": "Navamsa", "transit": "Transit", "divisional": "Divisional", "north_indian": "North Indian", "south_indian": "South Indian", "feature_unavailable": "This view is not available yet. Your deterministic Kundali data remains unchanged.", "unable_generate": "Unable to generate Kundli. Please verify the birth details.",
        "planet_details": "Planet Details", "sign_details": "Sign", "nakshatra_details": "Nakshatra", "retrograde": "Retrograde",
        "resolving": "Resolving birthplace and calculating the chart...", "chart_error": "The chart could not be calculated. Check the birth details and try again.", "chart_success": "Chart calculated for {place} ({timezone}).", "coordinates": "Coordinates", "birth_utc": "Birth UTC",
        "lagna": "Lagna", "moon_sign": "Moon sign", "sun_sign": "Sun sign", "planetary_positions": "Planetary positions", "twelve_houses": "Twelve houses (whole-sign)", "planet": "Planet", "longitude": "Longitude", "sign": "Sign", "degree": "Degree", "house": "House", "house_lord": "House Lord", "nakshatra": "Nakshatra", "pada": "Pada", "cusp": "Cusp",
        "d1_heading": "Lagna / D1 Chart", "d9_heading": "Navamsa / D9 Chart", "d10_heading": "Dashamsa / D10 Chart", "d1_caption": "Whole-sign houses; planet placement comes directly from the deterministic chart calculation.", "d9_caption": "Each D9 position is derived from the exact deterministic D1 sidereal longitude.", "d10_caption": "D10 positions derive deterministically from exact D1 sidereal longitudes using Parashara rules.", "d9_unavailable": "Navamsa data is unavailable for this chart.", "d10_unavailable": "Dashamsa data is unavailable for this chart.",
        "current_dasha": "Current Vimshottari Dasha", "mahadasha": "Mahadasha", "antardasha": "Antardasha", "timeline": "120-year Mahadasha timeline", "start_date": "Start Date", "end_date": "End Date", "antardasha_timeline": "{lord} Mahadasha - Antardasha timeline",
        "d1_d9": "D1 to D9 planet comparison", "d1_d10": "D1 to D10 planet comparison", "d1_sign": "D1 Sign", "d1_degree": "D1 Degree", "d9_sign": "D9 Sign", "d9_house": "D9 House", "d10_sign": "D10 Sign", "d10_house": "D10 House", "vargottama": "Vargottama", "yes": "Yes", "no": "No", "special_comparisons": "Special comparisons", "vargottama_summary": "Vargottama summary", "career_data": "Career analysis data",
        "tenth_house": "10th House", "tenth_lord": "10th House Lord", "tenth_lord_house": "10th Lord House", "planets_in_tenth": "Planets in 10th House", "d10_lagna": "D10 Lagna", "career_planets": "D10 career planet placements", "value": "Value",
        "ai_caption": "The model receives structured, deterministic chart JSON only. It cannot calculate or alter chart facts.", "generate_ai": "Generate AI interpretation", "ai_loading": "Generating an interpretation from the calculated chart...", "ai_error": "The AI interpretation is temporarily unavailable. Your calculated chart remains available.", "ai_setup": "AI interpretation is not configured. Copy `.env.example` to `.env` and set `OPENAI_API_KEY`.", "calculated_cues": "Calculated chart cues",
        "chat_tab": "AI Chat", "chat_title": "Ask about your Kundali", "chat_caption": "Answers use only your calculated chart facts and astrology-based interpretation.", "chat_input": "Ask a question about your Kundali...", "clear_chat": "Clear Chat", "suggested_questions": "Suggested questions", "chat_loading": "Reading your calculated Kundali...", "chat_unavailable": "AI Chat is unavailable. Please configure your OpenAI API key.", "chat_error": "AI Chat is temporarily unavailable. Please try again.", "suggest_dasha": "Explain my current Mahadasha", "suggest_career": "Analyze my career", "suggest_d10": "What does my D10 chart indicate?", "suggest_d9": "Explain my Navamsa chart", "suggest_finance": "What are my financial tendencies?",
        "new_chat": "New Chat", "conversations": "Conversations", "memory_unavailable": "Persistent chat memory is unavailable until DATABASE_URL is configured.",
        "invalid_time": "Please provide a time of birth.", "invalid_date": "{day} {month} {year} is not a valid calendar date.", "name_short": "Name must contain at least 2 characters.", "name_chars": "Name may contain only letters, spaces, and hyphens.", "dob_future": "Date of birth cannot be in the future.", "invalid_gender": "Please choose a valid gender.", "place_short": "Place of birth must contain at least 2 characters.", "place_network": "Could not contact the place lookup service. Please try again.", "place_not_found": "Place of birth was not found. Include city, state, and country.", "timezone_not_found": "Could not determine a timezone for this place.",
        "career": "Career", "finance": "Finance", "marriage": "Marriage", "health": "Health", "education": "Education", "foreign_travel": "Foreign Travel", "personality": "Personality", "next_12_months": "Next 12 months overview",
    },
    "hi": {
        "language": "भाषा", "english": "English", "hindi": "हिंदी", "app_title": "कुंडली AI", "app_subtitle": "AI-आधारित वैदिक ज्योतिष और जन्म कुंडली विश्लेषण", "birth_details": "जन्म विवरण", "birth_summary": "जन्म सारांश", "birth_time": "जन्म समय", "generate_new": "साइडबार में जन्म विवरण भरें और अपनी कुंडली बनाएं।", "app_caption": "Swiss Ephemeris और लाहिरी अयनांश के साथ सायडीरियल वैदिक गणनाएं।",
        "name": "नाम", "dob": "जन्म तिथि", "day": "दिन", "month": "माह", "year": "वर्ष", "time": "जन्म समय", "gender": "लिंग", "place": "जन्म स्थान", "generate": "कुंडली बनाएं",
        "select_gender": "लिंग चुनें", "female": "महिला", "male": "पुरुष", "non_binary": "नॉन-बाइनरी", "prefer_not": "बताना नहीं चाहते",
        "overview": "सारांश", "d1_tab": "लग्न कुंडली (D1)", "d9_tab": "नवांश कुंडली (D9)", "d10_tab": "दशमांश कुंडली (D10)", "positions_tab": "ग्रह स्थिति", "dasha_tab": "विंशोत्तरी दशा", "ai_tab": "AI विश्लेषण",
        "basic": "मूल जानकारी", "charts": "कुंडली", "kp": "KP", "ashtakavarga": "अष्टकवर्ग", "dasha": "दशा", "report": "रिपोर्ट", "lagna": "लग्न", "navamsa": "नवांश", "transit": "गोचर", "divisional": "वर्ग कुंडली", "north_indian": "उत्तर भारतीय", "south_indian": "दक्षिण भारतीय", "feature_unavailable": "यह दृश्य अभी उपलब्ध नहीं है। आपकी निर्धारक कुंडली का डेटा अपरिवर्तित है।", "unable_generate": "कुंडली बनाने में समस्या आई। कृपया जन्म विवरण दोबारा जांचें।",
        "planet_details": "ग्रह विवरण", "sign_details": "राशि", "nakshatra_details": "नक्षत्र", "retrograde": "वक्री",
        "resolving": "जन्म स्थान खोजा जा रहा है और कुंडली की गणना हो रही है...", "chart_error": "कुंडली की गणना नहीं हो सकी। जन्म विवरण जांचें और फिर प्रयास करें।", "chart_success": "{place} ({timezone}) के लिए कुंडली तैयार है।", "coordinates": "निर्देशांक", "birth_utc": "जन्म UTC",
        "lagna": "लग्न", "moon_sign": "चंद्र राशि", "sun_sign": "सूर्य राशि", "planetary_positions": "ग्रह स्थिति", "twelve_houses": "बारह भाव (पूर्ण राशि)", "planet": "ग्रह", "longitude": "देशांतर", "sign": "राशि", "degree": "अंश", "house": "भाव", "house_lord": "भाव स्वामी", "nakshatra": "नक्षत्र", "pada": "चरण", "cusp": "भाव आरंभ",
        "d1_heading": "लग्न कुंडली / D1", "d9_heading": "नवांश कुंडली / D9", "d10_heading": "दशमांश कुंडली / D10", "d1_caption": "पूर्ण-राशि भाव; ग्रह स्थान निर्धारक कुंडली गणना से लिए गए हैं।", "d9_caption": "प्रत्येक D9 स्थान सटीक D1 सायडीरियल देशांतर से निकाला गया है।", "d10_caption": "D10 स्थान पराशर नियमों से सटीक D1 सायडीरियल देशांतर से निकाले गए हैं।", "d9_unavailable": "इस कुंडली के लिए नवांश डेटा उपलब्ध नहीं है।", "d10_unavailable": "इस कुंडली के लिए दशमांश डेटा उपलब्ध नहीं है।",
        "current_dasha": "वर्तमान विंशोत्तरी दशा", "mahadasha": "महादशा", "antardasha": "अंतर्दशा", "timeline": "120-वर्षीय महादशा समयरेखा", "start_date": "प्रारंभ तिथि", "end_date": "समाप्ति तिथि", "antardasha_timeline": "{lord} महादशा - अंतर्दशा समयरेखा",
        "d1_d9": "D1 से D9 ग्रह तुलना", "d1_d10": "D1 से D10 ग्रह तुलना", "d1_sign": "D1 राशि", "d1_degree": "D1 अंश", "d9_sign": "D9 राशि", "d9_house": "D9 भाव", "d10_sign": "D10 राशि", "d10_house": "D10 भाव", "vargottama": "वर्गोत्तम", "yes": "हां", "no": "नहीं", "special_comparisons": "विशेष तुलना", "vargottama_summary": "वर्गोत्तम सारांश", "career_data": "करियर विश्लेषण डेटा",
        "tenth_house": "दसवां भाव", "tenth_lord": "दसवें भाव का स्वामी", "tenth_lord_house": "दसवें स्वामी का भाव", "planets_in_tenth": "दसवें भाव के ग्रह", "d10_lagna": "D10 लग्न", "career_planets": "D10 करियर ग्रह स्थान", "value": "मान",
        "ai_caption": "मॉडल को केवल संरचित और निर्धारक कुंडली JSON मिलता है। यह कुंडली तथ्यों की गणना या बदलाव नहीं कर सकता।", "generate_ai": "AI विश्लेषण बनाएं", "ai_loading": "गणना की गई कुंडली से विश्लेषण बनाया जा रहा है...", "ai_error": "AI विश्लेषण अभी उपलब्ध नहीं है। आपकी गणना की गई कुंडली उपलब्ध है।", "ai_setup": "AI विश्लेषण कॉन्फ़िगर नहीं है। `.env.example` को `.env` में कॉपी करें और `OPENAI_API_KEY` सेट करें।", "calculated_cues": "गणना किए गए कुंडली संकेत",
        "chat_tab": "AI चैट", "chat_title": "अपनी कुंडली के बारे में पूछें", "chat_caption": "उत्तर केवल आपके गणना किए गए कुंडली तथ्यों और ज्योतिषीय व्याख्या पर आधारित हैं।", "chat_input": "अपनी कुंडली के बारे में प्रश्न पूछें...", "clear_chat": "चैट साफ़ करें", "suggested_questions": "सुझाए गए प्रश्न", "chat_loading": "आपकी गणना की गई कुंडली पढ़ी जा रही है...", "chat_unavailable": "AI चैट उपलब्ध नहीं है। कृपया OpenAI API key कॉन्फ़िगर करें।", "chat_error": "AI चैट अभी उपलब्ध नहीं है। कृपया फिर प्रयास करें।", "suggest_dasha": "मेरी वर्तमान महादशा समझाइए", "suggest_career": "मेरे करियर का विश्लेषण करें", "suggest_d10": "मेरी D10 कुंडली क्या बताती है?", "suggest_d9": "मेरी नवांश कुंडली समझाइए", "suggest_finance": "मेरी आर्थिक स्थिति के बारे में बताइए",
        "new_chat": "नई चैट", "conversations": "वार्तालाप", "memory_unavailable": "DATABASE_URL कॉन्फ़िगर होने तक स्थायी चैट मेमोरी उपलब्ध नहीं है।",
        "invalid_time": "कृपया जन्म समय दें।", "invalid_date": "{day} {month} {year} मान्य कैलेंडर तिथि नहीं है।", "name_short": "नाम में कम से कम 2 अक्षर होने चाहिए।", "name_chars": "नाम में केवल अक्षर, स्थान और हाइफ़न हो सकते हैं।", "dob_future": "जन्म तिथि भविष्य की नहीं हो सकती।", "invalid_gender": "कृपया मान्य लिंग चुनें।", "place_short": "जन्म स्थान में कम से कम 2 अक्षर होने चाहिए।", "place_network": "जन्म स्थान सेवा से संपर्क नहीं हो सका। कृपया फिर प्रयास करें।", "place_not_found": "जन्म स्थान नहीं मिला। शहर, राज्य और देश शामिल करें।", "timezone_not_found": "इस स्थान के लिए समय क्षेत्र निर्धारित नहीं हो सका।",
        "career": "करियर", "finance": "वित्त", "marriage": "विवाह", "health": "स्वास्थ्य", "education": "शिक्षा", "foreign_travel": "विदेश यात्रा", "personality": "व्यक्तित्व", "next_12_months": "अगले 12 महीनों का सारांश",
    },
}

PLANETS_HI = {"Sun": "सूर्य", "Moon": "चंद्र", "Mars": "मंगल", "Mercury": "बुध", "Jupiter": "गुरु", "Venus": "शुक्र", "Saturn": "शनि", "Rahu": "राहु", "Ketu": "केतु"}
SIGNS_HI = {"Aries": "मेष", "Taurus": "वृषभ", "Gemini": "मिथुन", "Cancer": "कर्क", "Leo": "सिंह", "Virgo": "कन्या", "Libra": "तुला", "Scorpio": "वृश्चिक", "Sagittarius": "धनु", "Capricorn": "मकर", "Aquarius": "कुंभ", "Pisces": "मीन"}
NAKSHATRAS_HI = {"Ashwini": "अश्विनी", "Bharani": "भरणी", "Krittika": "कृत्तिका", "Rohini": "रोहिणी", "Mrigashira": "मृगशिरा", "Ardra": "आर्द्रा", "Punarvasu": "पुनर्वसु", "Pushya": "पुष्य", "Ashlesha": "आश्लेषा", "Magha": "मघा", "Purva Phalguni": "पूर्वा फाल्गुनी", "Uttara Phalguni": "उत्तरा फाल्गुनी", "Hasta": "हस्त", "Chitra": "चित्रा", "Swati": "स्वाति", "Vishakha": "विशाखा", "Anuradha": "अनुराधा", "Jyeshtha": "ज्येष्ठा", "Mula": "मूल", "Purva Ashadha": "पूर्वाषाढ़ा", "Uttara Ashadha": "उत्तराषाढ़ा", "Shravana": "श्रवण", "Dhanishta": "धनिष्ठा", "Shatabhisha": "शतभिषा", "Purva Bhadrapada": "पूर्व भाद्रपद", "Uttara Bhadrapada": "उत्तर भाद्रपद", "Revati": "रेवती"}


def t(key: str, lang: str = "en", **values: object) -> str:
    """Translate a key, falling back first to English and then to the key itself."""
    text = TRANSLATIONS.get(lang, TRANSLATIONS["en"]).get(key, TRANSLATIONS["en"].get(key, key))
    return text.format(**values)


def planet_name(name: str, lang: str) -> str:
    return PLANETS_HI.get(name, name) if lang == "hi" else name


def sign_name(name: str, lang: str) -> str:
    return SIGNS_HI.get(name, name) if lang == "hi" else name


def nakshatra_name(name: str, lang: str) -> str:
    return NAKSHATRAS_HI.get(name, name) if lang == "hi" else name
